[24/Nov/2019 16:19:49] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:21:14] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:21:14] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:21:14] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:21:14] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:21:14] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:21:14] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-0ab193f8-76d1-4262-b9e5-d0c579ef376b).
[24/Nov/2019 16:21:14] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:21:15] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:21:15] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:21:15] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:21:15] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:21:15] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:21:15] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:21:15] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:21:15] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:21:15] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:21:15] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:21:15] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:21:15] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:10] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:10] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:10] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:10] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:10] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:23:10] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:10] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:10] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:23:10] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:23:56] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:56] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:56] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:56] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:56] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:56] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:56] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:56] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:57] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:57] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:23:57] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:23:57] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:23:57] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:23:57] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:23:57] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:23:57] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:23:57] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:24:57] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:24:57] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:24:58] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:24:58] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:25:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:25:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:25:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:25:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:25:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:25:52] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-9faaee4e-6cba-4fe6-9b75-6dc45b9a42bd).
[24/Nov/2019 16:25:52] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:25:52] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:25:52] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:25:52] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:25:52] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:25:52] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:25:52] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:25:52] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:25:52] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:25:53] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:25:53] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:25:53] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:25:53] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:26:23] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:26:23] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:26:23] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:26:23] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:26:23] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:26:23] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:26:23] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:26:23] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:26:24] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:26:24] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:26:24] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:26:24] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:26:24] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:26:24] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:27:24] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:27:24] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:27:24] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:27:24] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:27:24] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:27:24] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-946c37e4-a31e-4108-8119-a22776686b79).
[24/Nov/2019 16:27:24] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:27:24] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:27:24] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:27:24] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:27:24] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:27:25] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:27:25] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:28:49] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:28:49] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:28:49] DEBUG [fs.btrfs:1472] mntpt: ['24K', '']
[24/Nov/2019 16:28:49] DEBUG [fs.btrfs:1476] KTTT: 24576
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:28:49] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:28:49] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:28:49] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:30:50] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:30:50] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:30:50] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:30:50] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:30:50] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:30:50] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-2efdea74-4abf-4fa9-8798-818c5f7e448e).
[24/Nov/2019 16:30:50] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:30:51] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:30:51] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:30:51] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:30:51] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:30:51] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:30:51] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:31:51] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:31:51] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:31:52] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:31:52] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:32:52] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:32:52] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:33:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:33:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:33:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:33:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:33:52] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:33:52] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-bc64ea05-9937-4322-895b-a1f47052380a).
[24/Nov/2019 16:33:52] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:34:53] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:34:53] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:34:53] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:34:53] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:34:53] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:34:53] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-a355f2e8-f257-4a1e-bf84-7d6ceda078bb).
[24/Nov/2019 16:34:53] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:34:53] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:34:53] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:35:54] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:35:54] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:35:54] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:35:54] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:35:54] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:35:54] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-40b08926-b36f-4b6a-9b24-9663eb84eace).
[24/Nov/2019 16:35:54] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:35:54] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:35:54] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:36:37] DEBUG [storageadmin.models.pool:87] POOLLLLLL
[24/Nov/2019 16:36:37] DEBUG [storageadmin.models.pool:88] 252706816
[24/Nov/2019 16:37:55] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:37:55] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:37:55] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:37:55] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:37:55] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:37:55] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-0041c970-8d99-41f5-9d8d-8ae872c57db3).
[24/Nov/2019 16:37:55] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:37:56] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:37:56] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:37:56] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:37:56] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:37:56] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:37:56] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:38:56] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:38:56] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:40:57] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:40:57] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:40:57] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:40:57] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:40:57] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:40:57] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-6c60cc28-d30e-4512-b6e8-b38cd5568f44).
[24/Nov/2019 16:40:57] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:41:58] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:41:58] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:41:58] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:41:58] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:41:58] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:41:58] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-be06c630-24d4-422e-81cb-83ebe2498ead).
[24/Nov/2019 16:41:58] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:41:58] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:41:58] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:41:58] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-share-state method: POST
[24/Nov/2019 16:41:58] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 345, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 86, in import_shares
    shares_in_pool = shares_info(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 666, in shares_info
    snap_idmap = snapshot_idmap(pool_mnt_pt)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 634, in snapshot_idmap
    out, e, rc = run_command([BTRFS, 'subvolume', 'list', '-s', pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-s', '0']): [Errno 2] No such file or directory
[24/Nov/2019 16:41:59] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:41:59] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:45:00] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:45:00] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:45:00] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:45:00] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:45:00] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:45:00] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-338e5e22-9730-45d4-9c64-5aa732b25440).
[24/Nov/2019 16:45:00] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:45:00] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:45:00] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:45:01] ERROR [storageadmin.middleware:32] Exception occurred while processing a request. Path: /api/commands/refresh-snapshot-state method: POST
[24/Nov/2019 16:45:01] ERROR [storageadmin.middleware:33] Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 350, in post
    import_snapshots(share)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 209, in import_snapshots
    share.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 765, in snaps_info
    pool_mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'subvolume', 'list', '-u', '-p', '-q', '/pwwwww']): [Errno 2] No such file or directory
[24/Nov/2019 16:47:01] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:47:01] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:47:01] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:47:01] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:47:01] DEBUG [system.osi:423] -- Skipping non root btrfs partition -
[24/Nov/2019 16:47:01] INFO [storageadmin.views.disk:107] Deleting duplicate or fake (by serial) disk db entry. Serial = (fake-serial-a296387a-c492-4564-a1c6-2f3500604e7f).
[24/Nov/2019 16:47:02] ERROR [system.osi:1623] Device (centos-root) not found by command (['/usr/sbin/udevadm', 'info', '--query=property', '--name', 'centos-root'])
[24/Nov/2019 16:47:02] ERROR [storageadmin.views.command:99] Exception while refreshing state for Pool(pwwwww). Moving on: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
[24/Nov/2019 16:47:02] ERROR [storageadmin.views.command:100] Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 80, in _refresh_pool_state
    is_root_pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 276, in get_pool_info
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['sss', 'fi', 'show', '/dev/disk/by-id/wwn-0x6000c295dc8766d3d5e899a614c0c331']): [Errno 2] No such file or directory
